sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t invicit/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true invicit/react-test npm test -- --coverage

after_success:
    - docker build -t invicit/multi-client -f ./client
    - docker build -t invicit/multi-nginx -f ./nginx
    - docker build -t invicit/multi-server -f ./server
    - docker build -t invicit/multi-worker -f ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push invicit/multi-client
    - docker push invicit/multi-nginx
    - docker push invicit/multi-server
    - docker push invicit/multi-worker